### ISSUE TITLE
Joomla 4 -- Message: Cannot access protected property Joomla\CMS\Menu\MenuItem::$params 

### ISSUE THREAD

**Issue by uglyeoin** [litespeedtech/lscache-joomla#51]
A PHP Exception occurred on your site. Here you can find the stack trace:
Exception Type: Error
File: /home/**********/public_html/plugins/system/lscache/lscache.php
Line: 143
Message: Cannot access protected property Joomla\CMS\Menu\MenuItem::$params 
#0 /home/**********/public_html/libraries/src/Plugin/CMSPlugin.php(285): plgSystemLSCache->onAfterRoute()
#1 /home/**********/public_html/libraries/vendor/joomla/event/src/Dispatcher.php(486): Joomla\CMS\Plugin\CMSPlugin->Joomla\CMS\Plugin\{closure}()
#2 /home/**********/public_html/libraries/src/Application/EventAware.php(111): Joomla\Event\Dispatcher->dispatch()
#3 /home/**********/public_html/libraries/src/Application/CMSApplication.php(1121): Joomla\CMS\Application\WebApplication->triggerEvent()
#4 /home/**********/public_html/libraries/src/Application/SiteApplication.php(820): Joomla\CMS\Application\CMSApplication->route()
#5 /home/**********/public_html/libraries/src/Application/SiteApplication.php(228): Joomla\CMS\Application\SiteApplication->route()
#6 /home/**********/public_html/libraries/src/Application/CMSApplication.php(278): Joomla\CMS\Application\SiteApplication->doExecute()
#7 /home/**********/public_html/includes/app.php(63): Joomla\CMS\Application\CMSApplication->execute()
#8 /home/**********/public_html/index.php(32): require_once('/home/argusacco...')
#9 {main}
Request information
GET variables
Array
(
)
POST variables
Array
(
)
COOKIE variables
Array
(
)
REQUEST variables
Array
(
)
SERVER variables
Array
(
    [PATH] => /usr/local/bin:/bin:/usr/bin
    [HTTP_ACCEPT] => */*

    [HTTP_USER_AGENT] => lscache_runner

    [REMOTE_ADDR] => 5.134.13.32
    [REMOTE_PORT] => 55588
    [SERVER_ADDR] => 5.134.13.32

    [SERVER_PORT] => 443
    [REQUEST_SCHEME] => https
    [REQUEST_URI] => /insights-all
    [REDIRECT_URL] => /insights-all
    [HTTPS] => on
    [HTTP_AUTHORIZATION] => 
    [REDIRECT_STATUS] => 200
    [SSL_PROTOCOL] => TLSv1.3
    [SSL_CIPHER] => TLS_AES_256_GCM_SHA384
    [SSL_CIPHER_USEKEYSIZE] => 256
    [SSL_CIPHER_ALGKEYSIZE] => 256
    [SCRIPT_FILENAME] => /home/******/public_html/index.php
    [QUERY_STRING] => 
    [SCRIPT_URI] => https://www.*******.co.uk/insights-all
    [SCRIPT_URL] => /insights-all
    [SCRIPT_NAME] => /index.php
    [SERVER_PROTOCOL] => HTTP/1.1
    [SERVER_SOFTWARE] => LiteSpeed
    [REQUEST_METHOD] => GET
    [X-LSCACHE] => on,crawler
    [PHP_SELF] => /index.php
    [REQUEST_TIME_FLOAT] => 1654116144.0041
    [REQUEST_TIME] => 1654116144
)

[systeminfo-2022-06-01T21_47_22+01_00.txt](https://github.com/litespeedtech/lscache-joomla/files/8818633/systeminfo-2022-06-01T21_47_22%2B01_00.txt)

**Comment by uglyeoin** [comment]
If that is the case you should mark this as closed but I just got this error yesterdy and I'm using the latest version I think.

Unhandled exception - Error 
Contact 
A PHP Exception occurred on your site. Here you can find the stack trace:

Exception Type: Error
File: /home/baselinecollecti/public_html/plugins/system/lscache/lscache.php
Line: 143
Message: Cannot access protected property Joomla\CMS\Menu\MenuItem::$params

#0 /home/baselinecollecti/public_html/libraries/src/Plugin/CMSPlugin.php(284): plgSystemLSCache->onAfterRoute()
#1 /home/baselinecollecti/public_html/libraries/vendor/joomla/event/src/Dispatcher.php(486): Joomla\CMS\Plugin\CMSPlugin->Joomla\CMS\Plugin\{closure}()
#2 /home/baselinecollecti/public_html/libraries/src/Application/EventAware.php(111): Joomla\Event\Dispatcher->dispatch()
#3 /home/baselinecollecti/public_html/libraries/src/Application/SiteApplication.php(790): Joomla\CMS\Application\WebApplication->triggerEvent()
#4 /home/baselinecollecti/public_html/libraries/src/Application/SiteApplication.php(232): Joomla\CMS\Application\SiteApplication->route()
#5 /home/baselinecollecti/public_html/libraries/src/Application/CMSApplication.php(293): Joomla\CMS\Application\SiteApplication->doExecute()
#6 /home/baselinecollecti/public_html/includes/app.php(61): Joomla\CMS\Application\CMSApplication->execute()
#7 /home/baselinecollecti/public_html/index.php(32): require_once('/home/baselinec...')
#8 {main}
Request information
GET variables
Array
(
)
POST variables
Array
(
)
COOKIE variables
Array
(
)
REQUEST variables
Array
(
)
SERVER variables
Array
(
    [PATH] => /usr/local/bin:/bin:/usr/bin
    [HTTP_ACCEPT] => */*
    [HTTP_HOST] => www.baselinecollective.com
    [HTTP_USER_AGENT] => lscache_runner
    [HTTP_X_HTTPS] => 1
    [DOCUMENT_ROOT] => /home/baselinecollecti/public_html
    [REMOTE_ADDR] => 5.134.13.32
    [REMOTE_PORT] => 45320
    [SERVER_ADDR] => 5.134.13.32
    [SERVER_NAME] => www.baselinecollective.com
    [SERVER_ADMIN] => webmaster@baselinecollective.com
    [SERVER_PORT] => 443
    [REQUEST_SCHEME] => https
    [REQUEST_URI] => /contact-alias
    [REDIRECT_URL] => /contact-alias
    [REDIRECT_REQUEST_METHOD] => GET
    [HTTPS] => on
    [HTTP_AUTHORIZATION] => 
    [REDIRECT_STATUS] => 200
    [X_SPDY] => HTTP2
    [SSL_PROTOCOL] => TLSv1.3
    [SSL_CIPHER] => TLS_AES_256_GCM_SHA384
    [SSL_CIPHER_USEKEYSIZE] => 256
    [SSL_CIPHER_ALGKEYSIZE] => 256
    [SCRIPT_FILENAME] => /home/baselinecollecti/public_html/index.php
    [QUERY_STRING] => 
    [SCRIPT_URI] => https://www.baselinecollective.com/contact-alias
    [SCRIPT_URL] => /contact-alias
    [SCRIPT_NAME] => /index.php
    [SERVER_PROTOCOL] => HTTP/1.1
    [SERVER_SOFTWARE] => LiteSpeed
    [REQUEST_METHOD] => GET
    [X-LSCACHE] => on,crawler
    [PHP_SELF] => /index.php
    [REQUEST_TIME_FLOAT] => 1685477005.038
    [REQUEST_TIME] => 1685477005
)
